version: '3.8'

services:
  api:
    build: .
    container_name: azul_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:senha123@db:5432/azulstreet
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=chave_secreta_super_segura_2026
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads

  db:
    image: postgres:15-alpine
    container_name: azul_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: azulstreet
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: azul_cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
